# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('nit', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nit', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Radicacion',
            fields=[
                ('factura', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateTimeField()),
                ('valor_factura', models.IntegerField()),
                ('tipo_contrato', models.BooleanField(default=False)),
                ('convenio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Convenio')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='radicacion',
            name='servicio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stc.Servicio'),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='unidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Unidad'),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convenio',
            name='ejecutivo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Ejecutivo'),
        ),
    ]
