# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenio',
            old_name='ejecutivo_id',
            new_name='ejecutivo',
        ),
        migrations.RenameField(
            model_name='radicacion',
            old_name='convenio_id',
            new_name='convenio',
        ),
        migrations.RenameField(
            model_name='radicacion',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='radicacion',
            old_name='servicio_id',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='radicacion',
            old_name='unidad_id',
            new_name='unidad',
        ),
        migrations.RenameField(
            model_name='radicacion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
