# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0002_auto_20160830_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stc.Empresa'),
        ),
    ]
