# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0003_auto_20160830_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacion',
            name='fecha_registro',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='mes_servicio',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='ejecutivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stc.Ejecutivo'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nit',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.IntegerField(),
        ),
    ]
