# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0004_auto_20160830_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefUnidad',
            fields=[
                ('referencia', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Unidad')),
            ],
        ),
    ]
