# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0007_auto_20160830_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacion',
            name='fecha_radicacion',
            field=models.CharField(max_length=10),
        ),
    ]
