# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0012_auto_20160902_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stc.Radicacion'),
        ),
    ]
