# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0017_devolucion_fecha_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_registro',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
