# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0018_auto_20160906_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='detalle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='gestion',
            field=models.CharField(max_length=250),
        ),
    ]
