# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0020_auto_20160914_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacion',
            name='fecha_radicacion',
            field=models.DateField(),
        ),
    ]
