# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0021_auto_20160914_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_devolucion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_gestion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_registro',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_remitido',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='fecha_glosa',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='fecha_ratificacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='fecha_remitido',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='fecha_respuesta_lim',
            field=models.DateField(),
        ),
    ]
