# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0022_auto_20160914_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='fecha_registro',
            field=models.DateTimeField(null=True),
        ),
    ]
