# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0024_auto_20160914_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glosa',
            old_name='fecha_respuesta_lim',
            new_name='fecha_max_respuesta',
        ),
        migrations.AddField(
            model_name='glosa',
            name='fecha_max_respuesta_rat',
            field=models.DateField(null=True),
        ),
    ]
