# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0025_auto_20160914_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='respuestaratificacion',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
    ]
