# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0026_auto_20160914_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
