# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0027_respuesta_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosaRespuesta',
            fields=[
                ('glosa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stc.Glosa')),
                ('gestion', models.CharField(max_length=250)),
                ('aceptado_ips', models.IntegerField()),
                ('fecha_registro', models.DateField(null=True)),
                ('codigo_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Causal')),
            ],
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='cerrado',
            new_name='locked',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='aceptado_ips',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='codigo_respuesta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='glosa',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='convenio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stc.Convenio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stc.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glosarespuesta',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.Respuesta'),
        ),
    ]
