# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0029_remove_respuesta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
