# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0031_respuesta_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosaActualizacion',
            fields=[
                ('glosa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stc.Glosa')),
                ('gestion', models.CharField(max_length=512)),
                ('fecha_actualizacion', models.DateField()),
                ('aceptado_ips', models.FloatField()),
                ('fecha_registro', models.DateField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='detalle',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='gestion',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='glosarespuesta',
            name='gestion',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='respuestaratificacion',
            name='gestion',
            field=models.CharField(max_length=512),
        ),
    ]
