# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0032_auto_20161010_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosa',
            name='saldo_glosa',
            field=models.PositiveIntegerField(),
        ),
    ]
