# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0033_auto_20161010_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespuestaRatificacion',
            new_name='GlosaRespRatif',
        ),
        migrations.AlterField(
            model_name='glosaactualizacion',
            name='aceptado_ips',
            field=models.IntegerField(),
        ),
    ]
