# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0034_auto_20161010_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosa',
            name='fecha_max_respuesta_rat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='fecha_ratificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
