# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0035_auto_20161011_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='fisico',
            field=models.BooleanField(default=True),
        ),
    ]
