# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0036_devolucion_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacion',
            name='special_code',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
